
### 
POST http://localhost:3000/api/mail HTTP/1.1
Content-Type: application/json

{
    "to": "georg.zsolnai123@gmail.com",
    "subject": "Testing nodemailer",
    "html": "<p>Why did you leave me</p>"
}